# Generated by Django 5.0.4 on 2024-04-24 14:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', models.TextField(verbose_name='Текст Новостей')),
                ('imge', models.ImageField(upload_to='post_img/', verbose_name='Картинуа поста')),
                ('slug', models.SlugField(unique=True, verbose_name='сылка')),
                ('created_ta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата создания поста')),
            ],
        ),
    ]
