# Generated by Django 5.0.4 on 2024-04-24 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Novost', 'verbose_name_plural': 'Novosti'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='imge',
            new_name='image',
        ),
    ]
