# Generated by Django 5.0.4 on 2024-05-08 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_rename_imge_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Nazvanie kategorii')),
                ('image', models.ImageField(upload_to='cat_img/', verbose_name='kartinka kategorii')),
                ('slug', models.SlugField(unique=True, verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Katigorii',
            },
        ),
        migrations.AddField(
            model_name='post',
            name='feature',
            field=models.BooleanField(default=False, verbose_name=' в слайдере'),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
